export const DUMMY_ALARM_CONTENTS = [
  {
    id: 0,
    title: '신청하신 민원이 접수되었어요!',
    category: '민원신청',
    detailInfo: '질서저해',
    created: '2/19 18:45',
    isFirstVisible: true,
  },
  {
    id: 1,
    title: '작성하신 게시물에 댓글이 달렸어요!',
    category: '2호선 게시판',
    detailInfo: '아하철 꿀팁',
    created: '2/19 18:45',
    isFirstVisible: false,
  },
  {
    id: 2,
    title: '신청하신 민원이 접수되었어요!',
    category: '민원신청',
    detailInfo: '질서저해',
    created: '2/19 18:45',
    isFirstVisible: true,
  },
  {
    id: 3,
    title: '신청하신 민원이 접수되었어요!',
    category: '민원신청',
    detailInfo: '질서저해',
    created: '2/19 18:45',
    isFirstVisible: true,
  },
  {
    id: 4,
    title: '신청하신 민원이 접수되었어요!',
    category: '민원신청',
    detailInfo: '질서저해',
    created: '2/19 18:45',
    isFirstVisible: true,
  },
  {
    id: 5,
    title: '작성하신 게시물에 댓글이 달렸어요!',
    category: '2호선 게시판',
    detailInfo: '오늘 1호선 왜이럼',
    created: '2/19 18:45',
    isFirstVisible: false,
  },
  {
    id: 6,
    title: '작성하신 게시물에 댓글이 달렸어요!',
    category: '2호선 게시판',
    detailInfo: '아지매 지나가요',
    created: '2/19 18:45',
    isFirstVisible: false,
  },
  {
    id: 7,
    title: '신청하신 민원이 접수되었어요!',
    category: '민원신청',
    detailInfo: '질서저해',
    created: '2/19 18:45',
    isFirstVisible: true,
  },
  {
    id: 8,
    title: '신청하신 민원이 접수되었어요!',
    category: '민원신청',
    detailInfo: '질서저해',
    created: '2/19 18:45',
    isFirstVisible: true,
  },
  {
    id: 9,
    title: '신청하신 민원이 접수되었어요!',
    category: '민원신청',
    detailInfo: '질서저해',
    created: '2/19 18:45',
    isFirstVisible: true,
  },
  {
    id: 10,
    title: '작성하신 게시물에 댓글이 달렸어요!',
    category: '2호선 게시판',
    detailInfo: '그걸 몰랐네',
    created: '2/19 18:45',
    isFirstVisible: false,
  },
  {
    id: 11,
    title: '작성하신 게시물에 댓글이 달렸어요!',
    category: '2호선 게시판',
    detailInfo: '새벽 5시 잠들지않아',
    created: '2/19 18:45',
    isFirstVisible: false,
  },
]

export const DUMMY_DM_CONTENTS = [
  {
    id: 0,
    nickname: 'GILDONGHONG',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: true,
  },
  {
    id: 1,
    nickname: 'GILDONGHONG',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 2,
    nickname: 'GILDONGHONG',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 3,
    nickname: 'GILDONGHONG',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 4,
    nickname: 'GILDONGHONG',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 5,
    nickname: 'GILDONGHONG어요!',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 6,
    nickname: 'GILDONGHONG어요!',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 7,
    nickname: 'GILDONGHONG',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 8,
    nickname: 'GILDONGHONG',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 9,
    nickname: 'GILDONGHONG',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 10,
    nickname: 'GILDONGHONG어요!',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
  {
    id: 11,
    nickname: 'GILDONGHONG어요!',
    content: '안녕하세요. 올려주신 지갑 제가 4호선에서 분실한 것 같은데 혹시 어디 거주하시나요? 제가 찾으러 가겠 ...',
    created: '2/19 18:45',
    hasNewMessage: false,
  },
]
