export const ARTICLE_DUMMY_LIST = [
  {
    _id: 1,
    title: '오늘자 3호선 빌런 출현',
    img_url: '/dummy/images/dummy1.png',
    content: '대통령은 조국의 평화적 통일을 위한 성실한 의무를 진다. 제1항의 해임건의는 국회재적의원 3분의 ...',
    author: '홍길동',
    likeCnt: 97,
    comment: 132,
    time: '2023-05-05T19:40:00.000Z',
  },
  {
    _id: 2,
    title: '지금 신분당 안오는 이유',
    img_url: null,
    content: '언론·출판은 타인의 명예나 권리 또는 공중도덕이나 사회윤리를 침해하여서는...',
    author: '홍길동',
    likeCnt: 90,
    comment: 97,
    time: '2023-05-05T10:00:00.000Z',
  },
  {
    _id: 3,
    title: '중앙역 앞 맛집 모음 리스트',
    img_url: '/dummy/images/dummy2.png',
    content: '언론·출판은 타인의 명예나 권리 또는 공중도덕이나 사회윤리를 침해하여서는...',
    author: '홍길동',
    likeCnt: 81,
    comment: 84,
    time: '2023-05-05T10:20:00.000Z',
  },
  {
    _id: 4,
    title: '노마스크충들 봐라',
    img_url: '/dummy/images/dummy3.png',
    content: '언론·출판은 타인의 명예나 권리 또는 공중도덕이나 사회윤리를 침해하여서는...',
    author: '홍길동',
    likeCnt: 58,
    comment: 75,
    time: '2023-05-05T09:40:00.000Z',
  },
  {
    _id: 5,
    title: '출근하는 길에 보기 좋은 책 모음',
    img_url: null,
    content: '대통령은 조국의 평화적 통일을 위한 성실한 의무를 진다. 제1항의 해임건의는 국회재적의원 3분의 ...',
    author: '홍길동',
    likeCnt: 35,
    comment: 70,
    time: '2023-05-05T10:43:00.000Z',
  },
  {
    _id: 6,
    title: '지금 신분당 안오는 이유',
    img_url: null,
    content: '언론·출판은 타인의 명예나 권리 또는 공중도덕이나 사회윤리를 침해하여서는...',
    author: '홍길동',
    likeCnt: 90,
    comment: 97,
    time: '2023-05-05T10:00:00.000Z',
  },
  {
    _id: 7,
    title: '중앙역 앞 맛집 모음 리스트',
    img_url: '/dummy/images/dummy2.png',
    content: '언론·출판은 타인의 명예나 권리 또는 공중도덕이나 사회윤리를 침해하여서는...',
    author: '홍길동',
    likeCnt: 81,
    comment: 84,
    time: '2023-05-05T10:20:00.000Z',
  },
  {
    _id: 8,
    title: '노마스크충들 봐라',
    img_url: '/dummy/images/dummy3.png',
    content: '언론·출판은 타인의 명예나 권리 또는 공중도덕이나 사회윤리를 침해하여서는...',
    author: '홍길동',
    likeCnt: 58,
    comment: 75,
    time: '2023-05-05T09:40:00.000Z',
  },
  {
    _id: 9,
    title: '출근하는 길에 보기 좋은 책 모음',
    img_url: null,
    content: '대통령은 조국의 평화적 통일을 위한 성실한 의무를 진다. 제1항의 해임건의는 국회재적의원 3분의 ...',
    author: '홍길동',
    likeCnt: 35,
    comment: 70,
    time: '2023-05-05T10:43:00.000Z',
  },
  {
    _id: 10,
    title: '중앙역 앞 맛집 모음 리스트',
    img_url: '/dummy/images/dummy2.png',
    content: '언론·출판은 타인의 명예나 권리 또는 공중도덕이나 사회윤리를 침해하여서는...',
    author: '홍길동',
    likeCnt: 81,
    comment: 84,
    time: '2023-05-05T10:20:00.000Z',
  },
  {
    _id: 11,
    title: '노마스크충들 봐라',
    img_url: '/dummy/images/dummy3.png',
    content: '언론·출판은 타인의 명예나 권리 또는 공중도덕이나 사회윤리를 침해하여서는...',
    author: '홍길동',
    likeCnt: 58,
    comment: 75,
    time: '2023-05-05T09:40:00.000Z',
  },
  {
    _id: 12,
    title: '출근하는 길에 보기 좋은 책 모음',
    img_url: null,
    content: '대통령은 조국의 평화적 통일을 위한 성실한 의무를 진다. 제1항의 해임건의는 국회재적의원 3분의 ...',
    author: '홍길동',
    likeCnt: 35,
    comment: 70,
    time: '2023-05-05T10:43:00.000Z',
  },
]

export const SEARCH_KEYWORD_DUMMY_LIST = [
  '1호선 연착',
  '교대맛집',
  '강남',
  '전장연',
  '1호선 연착',
  '교대맛집',
  '강남',
  '전장연',
  '1호선 연착',
  '교대맛집',
  '강남',
  '전장연',
]

export const HASH_TAG_DUMMY_LIST = [
  ['1호선 연착', '교대맛집', '강남', '전장연', '1호선 연착', '교대맛집'],
  ['강남', '전장연', '1호선 연착', '교대맛집', '강남', '전장연'],
]

export const ARTICLE_DETAIL_DUMMY_LIST = {
  _id: 1,
  title: '오늘자 3호선 빌런 출현',
  img_url: '/dummy/images/dummy1.png',
  content:
    '대통령은 조국의 평화적 통일을 위한 성실한 의무를 진다. 제1항의 해임건의는 국회재적의원 3분의 1 이상의 발의에 의하여 국회재적의원 과반수의 찬성이 있어야 한다.',
  time: '2023-05-05T19:40:00.000Z',
  author: '홍길동',
  likeCnt: 1,
  hateCnt: 0,
  commentCnt: 2,
  viewCnt: 3,
  hashtags: ['3호선', '3호선 빌런'],
}
