import 'react-lazy-load-image-component/src/effects/opacity.css';

import type { Metadata } from 'next';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { RQProvider, MSWComponent } from '@/app/_components';
import { Pretendard } from '@/common/assets/fonts/pretendard';
import { cn } from '@/common/utils/cn';

import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn('font-sans antialiased', Pretendard.variable)}>
        <MSWComponent />
        <RQProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </RQProvider>
      </body>
    </html>
  );
}
