import type { Metadata } from 'next';
<<<<<<< HEAD
import { NuqsAdapter } from 'nuqs/adapters/next/app';

=======
import '../globals.css';
import { RQProvider } from '../_components/RQProvider';
import { MSWComponent } from '../_components/MSWComponent';
>>>>>>> main
import { cn } from '@/common/utils/cn';
import { RQProvider, MSWComponent } from '@/app/_components';
import { Pretendard } from '@/common/assets/fonts/pretendard';

import '../globals.css';
import 'react-lazy-load-image-component/src/effects/opacity.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn('font-sans antialiased', Pretendard.variable)}>
        <MSWComponent />
<<<<<<< HEAD
        <RQProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </RQProvider>
=======
        <RQProvider>{children}</RQProvider>
>>>>>>> main
      </body>
    </html>
  );
}
