compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  local-pkg@*:
    dependencies:
      happy-dom: ^12.5.0
  swiper@*:
    dependencies:
      "react": "^18.2.0"
  redux-persist@*:
    dependencies:
      "redux": "^5.0.0"
  '@reach/portal@*':
    dependencies:
      "react-dom": "^18.2.0"
  
     
yarnPath: .yarn/releases/yarn-4.1.1.cjs

