yarnPath: .yarn/releases/yarn-4.1.1.cjs

packageExtensions:
  'local-pkg@*':
    dependencies:
      happy-dom: ^12.5.0
  'swiper@*':
    dependencies:
      'react': '^18.2.0'
  'redux-persist@*':
    dependencies:
      'redux': '^5.0.0'
  '@reach/portal@*':
    dependencies:
      'react-dom': '^18.2.0'
  '@lexical/react@*':
    dependencies:
      '@lexical/html': '^0.14.2'
  '@lexical/rich-text@*':
    dependencies:
      '@lexical/clipboard': '^0.14.2'
      '@lexical/selection': '^0.14.2'
  'eslint-config-next@*':
    dependencies:
      'next': '*'
