const KEY = ['TRAIN'];

const TRAINS_REAL_TIME_LIST_KEY = [...KEY, 'REAL_TIME_LIST'];

const TRAIN_CONGESTION_KEY = [...KEY, 'CONGESTION'];

export { KEY, TRAINS_REAL_TIME_LIST_KEY, TRAIN_CONGESTION_KEY };
