import type { Metadata } from 'next';

import './globals.css';
import { RQProvider } from './_components/RQProvider';
import { MSWComponent } from './_components/MSWComponent';

import { cn } from '@/common/utils/cn';
import { Pretendard } from '@/common/assets/fonts/pretendard';
import { PathTracker } from './_components/PathTracker';
import { ErrorCatcher } from './_components/ErrorCatcher';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={cn('font-sans antialiased', Pretendard.variable)}>
        <MSWComponent />
        <ErrorCatcher>
          <RQProvider>
            {children}
            <PathTracker />
          </RQProvider>
        </ErrorCatcher>
      </body>
    </html>
  );
}
