import StyledComponentsRegistry from '@/lib/StyledComponentsRegistry';
import { PropsWithChildren } from 'react';
import { ThemeProvider } from 'styled-components';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko">
      <head></head>
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
