import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LostFound() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-black">
      LostFound
    </main>
  );
}
