import { Metadata } from 'next';
import LoginButton from './_component/LoginButton';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>App Login</h1>
      <LoginButton />
    </main>
  );
}
