const SUBWAY_LINES = [
  { name: '1호선', id: 1 },
  { name: '2호선', id: 2 },
  { name: '3호선', id: 3 },
  { name: '4호선', id: 4 },
  { name: '5호선', id: 5 },
  { name: '6호선', id: 6 },
  { name: '7호선', id: 7 },
  { name: '8호선', id: 8 },
  { name: '9호선', id: 9 },
  { name: '경강선', id: 10 },
  { name: '경의중앙선', id: 11 },
  { name: '경춘선', id: 12 },
  { name: '공항철도', id: 13 },
  { name: '서해선', id: 15 },
  { name: '수인분당선', id: 16 },
  { name: '신분당선', id: 18 },
  { name: '우이신설선', id: 20 },
  { name: '인천 1호선', id: 21 },
  { name: '인천 2호선', id: 22 },
  { name: '에버라인선', id: 23 },
  { name: '의정부선', id: 24 },
  { name: '김포골드선', id: 25 },
  { name: '신림선', id: 26 },
];

export default SUBWAY_LINES;
