name: CI-ahhachul-app

on:
  pull_request:
    paths:
      - 'apps/web/**'

env:
  CACHED_BUILD_PATHS: ${{ github.workspace }}/apps/web/.next
  BUILD_CACHE_KEY: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: ./.github/actions/yarn-install

      - name: Build web-app
        working-directory: apps/web
        run: |
          yarn build

      - name: Archive .next folder
        uses: actions/upload-artifact@v2
        with:
          name: next-build
          path: apps/web/.next

      - name: Analyze bundle sizes
        uses: transferwise/actions-next-bundle-analyzer@master
        with:
          workflow-id: ci-ahhachul-app.yml
          base-branch: develop
          working-directory: apps/web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
