name: APP CI

on:
  pull_request:
    paths:
      - 'packages/**'
      - 'services/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'nx.json'
      - 'tsconfig.base.json'
      - '.eslintrc.js'
      - '.github/workflows/**'

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_NODE_VERSION: '20.13.0'
  HUSKY: '0'
  NEXT_TELEMETRY_DISABLED: '1'
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  main:
    name: 🚀 CI Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔨 Setup Node.js
        uses: actions/setup-node@v4
        timeout-minutes: 1
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: 📦 Install Dependencies
        uses: ./.github/actions/pnpm-install
        timeout-minutes: 5

      - name: 🔄 Set Nx Base/Head
        uses: nrwl/nx-set-shas@v4

      - name: 🔑 Create Environment File
        timeout-minutes: 1
        run: |
          echo '${{ secrets.DEV_REACT_APP_CONFIG }}' > config.json
          echo '${{ secrets.DEV_ONE_APP_CONFIG }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > services/one-app/.env

      - name: 🚫 Validate API Endpoint Literal Policy
        run: pnpm validate:api-contract

      - name: 🏃 Run CI Tasks
        run: |
          pnpm nx affected --parallel=3 -t type-check,build,test,lint
