name: Build & Deploy Ahhachul Web

on:
  push:
    branches:
      - feat/sign-in
env:
  DEFAULT_NODE_VERSION: '20.14.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Set up environment variables for .env.production
        run: |
          echo '${{ secrets.NEXT_ENV_PROD_CONTENT }}' > config.json
          cat config.json | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> services/next.ahhachul.com/.env.production

      - name: Build only affected packages
        run: yarn affected:build --parallel=5

      - name: Log in to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

      - name: Build Docker image
        run: |
          docker build -f services/next.ahhachul.com/Dockerfile -t ${{ secrets.ECR_REPOSITORY_URI }}:latest
      - name: Push Docker image to Amazon ECR
        run: docker push ${{ secrets.ECR_REPOSITORY_URI }}:lates
      - name: Deploy Application
        run: aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.DEV_ECS_APP_SERVICE_NAME }} --force-new-deployment
